// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Data;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(ProductsApiContext))]
    [Migration("20241209151249_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductsApi.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Imageurl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Noofstocks")
                        .HasColumnType("int");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<double>("ProductRating")
                        .HasColumnType("float");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Imageurl = "https://th.bing.com/th?id=OIP.1lnPiC5kC4p5yZ0q8IGS9wHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&dpr=1.5&pid=3.1&rm=2",
                            Noofstocks = 17,
                            ProductCategory = "Electronics",
                            ProductDescription = "The AirPods (3rd generation) provide personalized spatial audio with dynamic head tracking and Dolby Atmos support, while being IPX4 rated for sweat and water resistance. With a Lightning Charging Case, they offer up to 6 hours of listening time and 30 hours total. Features include pinch-perfect control, always-on ‘Hey Siri’ functionality, and seamless pairing with Apple devices, allowing for automatic audio switching.",
                            ProductName = "Apple AirPods (3rd Generation) Wireless Ear Buds",
                            ProductPrice = 189.99000000000001,
                            ProductRating = 1.0,
                            SellerName = "Appario Retail Private Ltd"
                        },
                        new
                        {
                            ProductId = 2,
                            Imageurl = "https://media.kohlsimg.com/is/image/kohls/3583992_Black_White?wid=805&hei=805&op_sharpen=1",
                            Noofstocks = 11,
                            ProductCategory = "Fashion",
                            ProductDescription = "A closet staple, the Nike Sportswear Club Fleece men’s pullover hoodie combines classic style with the soft comfort of fleece for an elevated, everyday look that you really can wear every day.",
                            ProductName = "Men's Nike Sportswear Club Fleece Pullover Hoodie",
                            ProductPrice = 48.75,
                            ProductRating = 2.5,
                            SellerName = "Maruti Enterprises"
                        },
                        new
                        {
                            ProductId = 3,
                            Imageurl = "https://fdn2.gsmarena.com/vv/bigpic/realme-10-pro.jpg",
                            Noofstocks = 8,
                            ProductCategory = "Electronics",
                            ProductDescription = "oneplus 10 Pro+ 5G (Nebula Blue, 128 GB) (8 GB RAM)",
                            ProductName = "oneplus 10 Pro+ 5G (Nebula Blue, 128 GB) (8 GB RAM)",
                            ProductPrice = 150.0,
                            ProductRating = 3.0,
                            SellerName = "Oppo Mobiles India Private Limited"
                        },
                        new
                        {
                            ProductId = 4,
                            Imageurl = "https://m.media-amazon.com/images/I/51USDDRcTjL._AC_SX679_.jpg",
                            Noofstocks = 12,
                            ProductCategory = "Home & Kitchen",
                            ProductDescription = "Your Perfect Cup of Coffee, Every Time. Holds 8 US Cups--- Excellent for Home, Office, Restaurant, or Gathering. Our thermal carafe is made with durable high-quality stainless steel, triple-layer vacuum insulation, and sweat-free design with zero condensation.",
                            ProductName = "Heritage66 Thermal Coffee Carafe -Triple Wall Vacuum insulated Flask",
                            ProductPrice = 26.989999999999998,
                            ProductRating = 4.2000000000000002,
                            SellerName = "Vinod Cookware"
                        },
                        new
                        {
                            ProductId = 5,
                            Imageurl = "https://m.media-amazon.com/images/I/61J5Z-OYUUL._SY522_.jpg",
                            Noofstocks = 15,
                            ProductCategory = "Books",
                            ProductDescription = "Dear reader, I hope this book feels like a warm hug to you. I wrote this book for the ones who feel everything too deeply. This book was meant to find you if you’ve ever loved someone who didn’t love you back, or if you have a hard time letting go.",
                            ProductName = "I Don’t Love You Anymore: Moving On and Living Your Best Life",
                            ProductPrice = 12.99,
                            ProductRating = 5.0,
                            SellerName = "Penguin Ananda (8 October 2018)"
                        },
                        new
                        {
                            ProductId = 6,
                            Imageurl = "https://m.media-amazon.com/images/I/61iYG7ArviL._AC_UL480_FMwebp_QL65_.jpg",
                            Noofstocks = 10,
                            ProductCategory = "Watches",
                            ProductDescription = "Military Sport Design: Fashionable sporty dial design, military style outlook. Large Dial (acrylic crystal glass window, case diameter high-quality watch band, Reinforced resin band design is more ergonomic, comfortable to wear.",
                            ProductName = "KXAITO Men's Watches Sports Outdoor Waterproof Military Watch",
                            ProductPrice = 21.989999999999998,
                            ProductRating = 0.0,
                            SellerName = "Vee Ess Sales Pvt Ltd"
                        },
                        new
                        {
                            ProductId = 7,
                            Imageurl = "https://m.media-amazon.com/images/I/61i9Rwk3OhL._AC_UL480_FMwebp_QL65_.jpg",
                            Noofstocks = 9,
                            ProductCategory = "Perfume",
                            ProductDescription = "PURE FRAGRANCE POWDERY TOBACCO: Features the unique scent of tobacco leaves, highlighted by sweet honey and fruity notes with a touch of ginger.",
                            ProductName = "Dossier - Powdery Tobacco - Eau de Parfum",
                            ProductPrice = 39.0,
                            ProductRating = 0.0,
                            SellerName = "Vini Cosmetics"
                        },
                        new
                        {
                            ProductId = 8,
                            Imageurl = "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/electronics-software-and-accessories/accessories/dell/carrying-case/ecoloop-pro-slim-backpack-cp5724s/media-gallery/en/carrying-cases-backpack-ecoloop-cp5724s-gallery-1-en.psd?fmt=png-alpha&pscan=auto&scl=1&hei=476&wid=472&qlt=100,1&resMode=sharp2&size=472,476&chrss=full",
                            Noofstocks = 9,
                            ProductCategory = "Bags",
                            ProductDescription = "Get the Dell EcoLoop Pro Slim Backpack 15 that protects your gear on-the-go and helps reduce environmental impact.",
                            ProductName = "Dell EcoLoop Pro Slim Backpack 15",
                            ProductPrice = 49.990000000000002,
                            ProductRating = 4.2000000000000002,
                            SellerName = "Cannycom Store"
                        },
                        new
                        {
                            ProductId = 9,
                            Imageurl = "https://snpi.dell.com/snp/images/products/large/520-AAUL_MVI4.jpg",
                            Noofstocks = 8,
                            ProductCategory = "HeadPhones",
                            ProductDescription = "Experience exceptional audio clarity with this Teams certified wired headset that allows you to wear the microphone on either side for a customized fit.",
                            ProductName = "Dell Pro Stereo Headset | WH3022",
                            ProductPrice = 69.989999999999995,
                            ProductRating = 4.2000000000000002,
                            SellerName = "gadgets storm"
                        },
                        new
                        {
                            ProductId = 10,
                            Imageurl = "https://i.dell.com/is/image/DellContent//content/dam/ss2/product-images/dell-client-products/peripherals/monitors/s-series/s2722dc/media-gallery/s2722dc_cfp_00000ff090_gy.psd?fmt=png-alpha&pscan=auto&scl=1&hei=476&wid=476&qlt=100,1&resMode=sharp2&size=476,476&chrss=full",
                            Noofstocks = 8,
                            ProductCategory = "Monitors",
                            ProductDescription = "Feature Height Adjustment, Anti Glare Screen, Pivot Adjustment, USB Hub, High Dynamic Range.",
                            ProductName = "Dell 27 QHD Monitor (USB-C) | S2722DC",
                            ProductPrice = 259.99000000000001,
                            ProductRating = 4.2000000000000002,
                            SellerName = "BenQ, BenQ Corporation 16 Jihu Road, Neihu 114, Taipei, Taiwan"
                        },
                        new
                        {
                            ProductId = 11,
                            Imageurl = "https://jcpenney.scene7.com/is/image/JCPenney/DP0423202011002668M.tif?$gallery$&wid=350&hei=350&op_sharpen=1",
                            Noofstocks = 9,
                            ProductCategory = "Watches",
                            ProductDescription = "Case style: Analog watch with a stainless steel circular case Dial style: Black dial with silver hands Strap style: Stainless steel strap with a butterfly clasp for comfort and style.",
                            ProductName = "Citizen Diamond Maleficent Sleeping Beauty Womens Diamond Accent Black Stainless Steel Bracelet Watch",
                            ProductPrice = 32.850000000000001,
                            ProductRating = 4.0,
                            SellerName = "VRP Telematics"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
